---
services:
  docker-code-server:
    image: "${ECR_ACCOUNT_ID:-0123456789012}.dkr.ecr-fips.${ECR_REGION}.amazonaws.com/docker-code-server:${IMAGE_TAG:-latest}"
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      args:
        - ECR_ACCOUNT_ID=${ECR_ACCOUNT_ID:-0123456789012}
        - BASE_IMAGE_TAG=${BASE_IMAGE_TAG:-jammy-latest}
    env_file: ./.default_env
    ports:
      - "${HOST_PORT:-8443}:8443"
