---
services:
  code-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_DATE=${BUILD_DATE:-2025-01-21T00:00:00Z}
        - VERSION=${VERSION:-4.102.1}
        - CODE_RELEASE=${CODE_RELEASE:-4.102.1}
    image: gabemendoza1/codecloud-code-server:jammy-code-server-python-v${CODE_RELEASE:-4.102.1}
    container_name: code-server
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - PROXY_DOMAIN=${PROXY_DOMAIN:-}
      - DEFAULT_WORKSPACE=${DEFAULT_WORKSPACE:-/workspace}
      - PWA_APPNAME=${PWA_APPNAME:-code-server}
    ports:
      - "${HOST_PORT:-8443}:8443"
    restart: unless-stopped
