version: 0.2
phases:
  pre_build:
    commands:
      - export DOCKER_BUILDKIT=1
      - export ECR_ACCOUNT_ID="$(echo $FIPS_REPOSITORY_URI | cut -d'.' -f1)"
      - export ECR_REGION="$(echo $FIPS_REPOSITORY_URI | cut -d'.' -f4)"
  build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${FIPS_REPOSITORY_URI}
      - echo Building the Docker image...
      - docker build --build-arg ECR_ACCOUNT_ID=${ECR_ACCOUNT_ID} --build-arg ECR_REGION=${ECR_REGION} -t ${FIPS_REPOSITORY_URI}:latest .
      - docker image push --all-tags  ${FIPS_REPOSITORY_URI}
  post_build:
    commands:
      - echo Build completed!
